# Use an official GCC image
FROM gcc:latest

# Set the working directory
WORKDIR /app

# Copy the server code and the orderbook header file to the container
COPY server.cpp .
COPY OrderBook.h .

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    make \
    && rm -rf /var/lib/apt/lists/*

# Compile the server code
RUN g++ -o server server.cpp -pthread

# Command to run the server
CMD ["./server"]
